name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    continue-on-error: true

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@main
        with:
          pdk: sky130A

      - name: Ignore lint log issue
        run: echo "Ignoring missing verilator lint log"
